### ISSUE TITLE
Submit evaluations of other teams

### ISSUE THREAD

**Issue by trebi** [Qerts/pa165-java#4]
Evaluation Checklist:
- You can assign maximum 10 points to the project you are reviewing.
- -3 points if it is not possible to compile the project using “mvn clean install”. You must either make this work or ask the team to fix this ASAP because it’s hard to check the code without this.
- -1 point for each minor occurrence of a team member not contributing enough.
- -1 points for incorrectly implementing equals/hash code.
- -1 points for every minor occurrence of missing methods/tests (e.g. missing important method on a DAO object or a missing test for that method).
- If a team member was not contributing at all, or very little, you should explicitly say this in your evaluation report. Tutor will follow up on this information.

Each member evaluates a project of another team. To find out which project do you evaluate, check:
https://docs.google.com/spreadsheets/d/193LHasHryuDqN60cBUvBN8iH74GZgc7AQRreKV7FJKo/edit?usp=sharing

**Comment by JozeFe** [comment]
How to write another project’s evaluation

You will submit the evaluation as text document to the submission folder in information system /auth/el/1433/podzim2016/PA165/ode/. Use the submission folder for your seminar group, subfolder for the specific milestone and subfolder for the specific project. Add to the filename your name (or the way that will be communicated by your tutor to identify your submission, e.g. uco and surname might be added automatically to the file submission).

For each milestone, the tutor will assign you a project (another team’s project) that you must evaluate. Every student in your team will evaluate a different project assigned by your tutor and projects will rotate during milestones, so that by the end of the seminars you will have evaluated as many projects as possible.

You should use the checklist that will be part of each milestone to deduct points. Your evaluation should be a short text document, see the example below. In your evaluation you should mention why you are deducing points and how many. The conclusion of your evaluation should be how many points the project should receive for this milestone.

Example checklist:

Maximum number of points for this milestone are 10 points
-1 point project should be compilable from command line using “mvn compile”
-2 points for 5 hours late submission
Example evaluation:

evaluated project: github.com/XXXXYYY
uco, name, surname: 5555, myname, mysurname

a) Checklist evaluation:

-1 project was not compilable
-2 project was submitted 1 hour after deadline
total points: 7

b) General comments: we would like to suggest to write more extended comments, example for classes xxx and yyy. We generally found the number of test methods acceptable for the project, however we would suggest to improve the quality of tests for more critical parts of the project, example package zzz. The provided tests do not test the system when multiple entities are removed.
Really great work on the configuration of the project, we liked the idea to use the Dozer project for beans mapping.

c) Strong points of the project: great user-friendly user interface, very good exception handling throughout the project.

d) Weaknesses of the project: testing should be improved. Some parts of the application seem quite fragile and not reliable at all (example: classes abc and bcd). The project does not follow Java code conventions in several places (example: xxx).

e) other notes: It looks like Pet.java was copied from example project. Also it seems that Petr Lenoch was not contributing very much, he has only one commit in which he was formatting code.
